image:
  name: artifacts.saint-gobain.net/eai-000-docker-public-local/php:8.1.3
  entrypoint: [""]

variables:
  ARTIFACT_DIR: output

stages:
  - build
  - deploy

build_composer:
  stage: build
  artifacts:
    name: "$CI_PROJECT_NAME"
    paths:
      - $ARTIFACT_DIR/*
    expire_in: 5 days
  tags:
    - website_node
  script:
    - echo  "==== STARTING build JOB ===="
    #- export http_proxy=http://"$CLN_PROXY"
    #- export https_proxy=http://"$CLN_PROXY"
    - export APP_ENV=prod
    - echo  "==== Get composer ===="
    - curl -x "$CLN_PROXY" -o composer-setup.php https://getcomposer.org/installer
    #- php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    - php composer.phar --version
    - echo  "==== Get build tools  ===="
    - apt-get update && apt-get -y install unzip zip git 
    - echo  "==== Get dependencies ===="
    - php composer.phar install --ignore-platform-reqs  --no-dev --optimize-autoloader
    - echo  "==== Make assets ===="
    - php bin/console assets:install
    - echo  "==== Assets installed ===="
    - echo  "==== Remove working dir/files ===="
    - rm -rf .git*
    - rm -rf var/cache/prod
    - rm composer.phar
    - echo  "==== Make .env file ===="
    - cp .env.dist .env
    - sed -i 's;ELASTICSEARCH_SERVER_URL=http://localhost:9200;ELASTICSEARCH_SERVER_URL=<elasticsearch_url>;g' .env
    - sed -i 's;STAT_ELASTICSEARCH_SERVER_URL=http://localhost:9200;STAT_ELASTICSEARCH_SERVER_URL=<elasticsearch_url>;g' .env
    - sed -i 's;RECO_ELASTICSEARCH_SERVER_URL=http://localhost:9200;RECO_ELASTICSEARCH_SERVER_URL=<elasticsearch_url>;g' .env
    - sed -i 's;ADS_INDEX_NB_REPLICAS=0;ADS_INDEX_NB_REPLICAS=1;g' .env
    - sed -i 's;ADS_STAT_INDEX_NB_REPLICAS=0;ADS_STAT_INDEX_NB_REPLICAS=1;g' .env
    - sed -i 's;ADS_RECO_INDEX_NB_REPLICAS=0;ADS_RECO_INDEX_NB_REPLICAS=1;g' .env
    - sed -i 's;MAX_REPLICAS=0;MAX_REPLICAS=1;g' .env
    - sed -i 's;ADS_API_APPLY_BOOSTING=0;ADS_API_APPLY_BOOSTING=1;g' .env
    - sed -i 's;IS_LEGACY=0;IS_LEGACY=1;g' .env
    - sed -i 's;COLLECT_STATS=1;COLLECT_STATS=0;g' .env
    - echo  "==== Dir content ===="
    - ls -alh
    - ls -alh vendor
    - du -sh vendor/
    - echo  "==== Making artifact in $ARTIFACT_DIR dir ===="
    - zip -qr "$CI_PROJECT_NAME" *
    - zip "$CI_PROJECT_NAME".zip .env
    - ls -alh
    - mkdir $ARTIFACT_DIR
    - mv "$CI_PROJECT_NAME".zip ./$ARTIFACT_DIR
    - ls -alh
    - ls -alh $ARTIFACT_DIR
    - echo  "==== END OF build JOB ===="

  only:
    - master

deploy_jfrog:
  stage: deploy
  tags:
    - website_node
  script:
    - echo  "==== STARTING deploy JOB ===="
    - echo  "==== $ARTIFACT_DIR content ===="
    - ls -alh $ARTIFACT_DIR
    - echo  "==== Push artifact on $JFROG_REPO_COMPOSER repo ===="
    - curl -k -H "X-JFrog-Art-Api:$JFROG_API_KEY" "$JFROG_ARTIFACTORY"/"$JFROG_REPO_COMPOSER"/ -T  $ARTIFACT_DIR/"$CI_PROJECT_NAME".zip
    - echo  "==== deploy JOB ENDED ===="
  only:
    - master

