ARG ELS_TAG

# Elasticsearch
FROM elasticsearch:${ELS_TAG} AS els


RUN "mkdir -p /usr/share/backup/ && chown elasticsearch:root /usr/share/backup/" 
COPY .docker/config/elasticsearch/elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml