FROM webdevops/php-apache:7.2

ARG ELASTICSEARCH_SERVER_URL
ARG STAT_ELASTICSEARCH_SERVER_URL=$ELASTICSEARCH_SERVER_URL
ARG RECO_ELASTICSEARCH_SERVER_URL=$ELASTICSEARCH_SERVER_URL
ARG ADS_INDEX_NB_SHARDS=1
ARG ADS_INDEX_NB_REPLICAS=1
ARG ADS_STAT_INDEX_NB_SHARDS=1
ARG ADS_STAT_INDEX_NB_REPLICAS=1
ARG ADS_RECO_INDEX_NB_SHARDS=1
ARG ADS_RECO_INDEX_NB_REPLICAS=1
ARG ADS_API_APPLY_BOOSTING=0
ARG SYNONYMS_DICTIONARIES_PATH
ARG COLLECT_STATS=1

RUN apt-get update

RUN mkdir -p /var/log/apache2

RUN ln -snf /usr/share/zoneinfo/Europe/Paris /etc/localtime
RUN echo "Europe/Paris" > /etc/timezone

COPY .docker/conf/httpd/default.conf /opt/docker/etc/httpd/vhost.common.d/gt.conf
COPY .docker/conf/php/custom.ini /opt/docker/etc/php/php.ini

USER application

COPY --chown=application:application . /app

WORKDIR /app

RUN echo APP_ENV=prod > .env
RUN echo APP_SECRET=`cat /dev/urandom | tr -dc 'a-z0-9' | fold -w 32 | head -n 1` >>.env
RUN echo ELASTICSEARCH_SERVER_URL=$ELASTICSEARCH_SERVER_URL >>.env
RUN echo STAT_ELASTICSEARCH_SERVER_URL=$STAT_ELASTICSEARCH_SERVER_URL >>.env
RUN echo RECO_ELASTICSEARCH_SERVER_URL=$RECO_ELASTICSEARCH_SERVER_URL >>.env
RUN echo ADS_INDEX_NB_SHARDS=$ADS_INDEX_NB_SHARDS >>.env
RUN echo ADS_INDEX_NB_REPLICAS=$ADS_INDEX_NB_REPLICAS >>.env
RUN echo ADS_STAT_INDEX_NB_SHARDS=$ADS_STAT_INDEX_NB_SHARDS >>.env
RUN echo ADS_STAT_INDEX_NB_REPLICAS=$ADS_STAT_INDEX_NB_REPLICAS >>.env
RUN echo ADS_RECO_INDEX_NB_SHARDS=$ADS_RECO_INDEX_NB_SHARDS >>.env
RUN echo ADS_RECO_INDEX_NB_REPLICAS=$ADS_RECO_INDEX_NB_REPLICAS >>.env
RUN echo ADS_API_APPLY_BOOSTING=$ADS_API_APPLY_BOOSTING >>.env
RUN echo SYNONYMS_DICTIONARIES_PATH=$SYNONYMS_DICTIONARIES_PATH >>.env
RUN echo COLLECT_STATS=$COLLECT_STATS >>.env

RUN composer1 install

#docker build
#    --build-arg ELASTICSEARCH_SERVER_URL=elk:9200
#    -t adimeo-data-suite .