version: '3.7'
services:
    web:
        image: adimeotech/adimeo-data-suite:elk5.6_php8.0
        container_name: ads_web
        networks:
            - adimeo_local_proxy
        labels:
            - 'traefik.http.routers.ads.entrypoints=http'
            - 'traefik.http.routers.ads.rule=Host(`ads.dev.local`)'
            - 'traefik.http.middlewares.ads-https-redirect.redirectscheme.scheme=https'
            - 'traefik.http.routers.ads.middlewares=ads-https-redirect'
            - 'traefik.http.routers.ads-secure.entrypoints=https'
            - 'traefik.http.routers.ads-secure.rule=Host(`ads.dev.local`)'
            - 'traefik.http.routers.ads-secure.tls=true'
            - 'traefik.docker.network=adimeo_local_proxy'
        volumes:
            - ".:/var/www/html"
            - ./.docker/config/dev/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    elk:
        image: elasticsearch:5
        container_name: ads_elk
        volumes:
            - ads_data:/usr/share/elasticsearch/data
        environment:
            - discovery.type=single-node
            - network.host=0.0.0.0
            - discovery.seed_hosts=0.0.0.0
        networks:
            - adimeo_local_proxy

volumes:
    ads_data:

networks:
    adimeo_local_proxy:
        external: true
